spring.datasource.url=jdbc:postgresql://localhost:5432/New3
spring.datasource.username=postgres
spring.datasource.password=666
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create
server.port=8090
jwt.access-secret=super-static-secret-string-42-foo-bar-baz;
jwt.refresh-secret=super-static-secret-string-42-foo-bar-baz;
jwt.access-token-expiration-time=86400
jwt.refresh-token-expiration-time=2629800000
redis.hostname=localhost
redis.port=6379
cf.zone_id=a161a5f2ea5c3f149342c95cb51de234
cf.token=
cloud.subnet_id=enpsf4v5p43f4ek4f88d
cloud.folder_id=b1g4hasb5oc26qr7u1o5